### ISSUE TITLE
Why super(); in public RobopupuApplication()?

### ISSUE THREAD

**Issue by farmazon3000** [Fuusio/Robopupu#9]
Why super(); in public RobopupuApplication()?

`
public RobopupuApplication() {
    super();
}
`

https://github.com/Fuusio/Robopupu/blob/master/app/src/main/java/com/robopupu/app/RobopupuApplication.java

**Comment by Fuusio** [comment]
That `super()` call for the superclass constructor is not really needed, because the Java compiler would automatically insert a call to the no-argument constructor of the superclass anyway. Actually the entire `RobopupuApplication()` default constructor is not necessary at all. It can be removed. 

Class `RobopupuApplication` is part of sample application not Robopupu library, so there are still some bits to be polished. 

I will remove that default constructor entirely.

Thanks for notifying :)
